twitch_bot_name: "Kebirow"
twitch_bot_id: "682675045"

discord_bot_name: "Kebirow"
discord_bot_discriminator: "8705"

super_admin: "0mskbird"

# Channels - The bot will connect to all listed Twitch channels on startup
twitch_channels:
    - adixred
    - 0mskbird

## COMMON CONFIGS
# Specifies whether the bot can be triggered only when joined channel is live
active_on_live_stream_only: true

muted: false

active_features:
    - LOGGING
    - COMMAND
#    - SUBSCRIPTION
#    - MODERATOR
    - ALIVE

## FEATURE: ALIVE
# Defines whether Bot welcomes chat users
user_greeting_enabled: true
# Defines time in seconds which bot must wait after its last message before triggering via tagging can happen (excluding admins)
tag_trigger_max_wait_time: 15
# Defines time in seconds which bot must wait after its last message before self triggering can happen
self_trigger_max_wait_time: 60
# Additional keywords for indirect bot tagging
additional_bot_tag_names:
    - бот
    - бота
    - боту
    - ботом
    - боте
    - ботик
    - ботика
    - ботику
    - ботиком
    - ботике
    - кебиров
    - кебирова
    - кебирову
    - кебировым
    - bot
# Selected model for OpenAI response generator
openai_model: DAVINCI


## FEATURE: MODERATOR
# Channel permissions of users for skipping moderation
message_whitelisted_permissions:
    - BROADCASTER
    - MODERATOR
    - TWITCHSTAFF
    - VIP
    - SUBSCRIBER

# Specifies if bot should check whether it has moderator permissions or not before doing moderation activities
check_moderator_permissions: true

# Number threshold of suspicious words to trigger message check
moderation_word_number_threshold: 3

# Number of total points for a message to get timeout on channel
violation_points_threshold_for_timeout: 10

# Number of total points for a message to get banned on channel
violation_points_threshold_for_ban: 15

# Number of total points for a message to get banned on channel
violation_points_for_first_message: 5

# Time in seconds for automatic timeout in moderation mode
auto_timeout_time_seconds: 86400 # 24 hours
