CREATE SCHEMA TW_BOT;

-- Table for GlobalConfigurationEntity
CREATE TABLE TW_BOT.GLOBAL_CONFIG
(
    GLOBAL_CONFIG_ID                BIGINT(11)  NOT NULL AUTO_INCREMENT,
    GLOBAL_CONFIG_TIMESTAMP         BIGINT(11)  NOT NULL,
    GLOBAL_CONFIG_CREATION_TIME     DATETIME    NOT NULL,
    GLOBAL_CONFIG_CODE              VARCHAR(25) NOT NULL,
    GLOBAL_CONFIG_SUPER_ADMIN_ID    BIGINT(11)  NOT NULL,
    PRIMARY KEY (GLOBAL_CONFIG_ID)
);

-- Table for ChannelConfigurationEntity
CREATE TABLE TW_BOT.CHANNEL_CONFIG
(
    CHANNEL_CONFIG_ID               BIGINT(11)  NOT NULL AUTO_INCREMENT,
    CHANNEL_CONFIG_TIMESTAMP        BIGINT(11)  NOT NULL,
    CHANNEL_CONFIG_CREATION_TIME    DATETIME    NOT NULL,
    PRIMARY KEY (CHANNEL_CONFIG_ID)
);

-- Table for ChannelEntity
CREATE TABLE TW_BOT.CHANNEL
(
    CHANNEL_ID              BIGINT(11)  NOT NULL AUTO_INCREMENT,
    CHANNEL_TIMESTAMP       BIGINT(11)  NOT NULL,
    CHANNEL_CREATION_TIME   DATETIME    NOT NULL,
    CHANNEL_NAME            VARCHAR(25) NOT NULL,
    GLOBAL_CONFIG_ID        BIGINT(11)  NULL,
    CHANNEL_CONFIG_ID       BIGINT(11)  NULL,
    PRIMARY KEY (CHANNEL_ID),
    KEY SN_FK_CHANNEL_CONFIG_IDX (CHANNEL_CONFIG_ID),
    CONSTRAINT SN_FK_CHANNEL_CONFIG
        FOREIGN KEY (CHANNEL_CONFIG_ID)
            REFERENCES TW_BOT.CHANNEL_CONFIG (CHANNEL_CONFIG_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Table for BotFeatureEntity
CREATE TABLE TW_BOT.BOT_FEATURE_TYPE
(
    BOT_FEATURE_TYPE_ID              BIGINT(11)  NOT NULL AUTO_INCREMENT,
    BOT_FEATURE_TYPE_TIMESTAMP       BIGINT(11)  NOT NULL,
    BOT_FEATURE_TYPE_CREATION_TIME   DATETIME    NOT NULL,
    BOT_FEATURE_TYPE_CODE            VARCHAR(45) NOT NULL,
    PRIMARY KEY (BOT_FEATURE_TYPE_ID)
);

-- Table for ChannelBotFeatureConfigurationEntity
CREATE TABLE TW_BOT.CHANNEL_BOT_FEATURE_CONFIGURATION
(
    CHANNEL_BOT_FEATURE_CONFIGURATION_ID            BIGINT(11)  NOT NULL AUTO_INCREMENT,
    CHANNEL_BOT_FEATURE_CONFIGURATION_TIMESTAMP     BIGINT(11)  NOT NULL,
    CHANNEL_BOT_FEATURE_CONFIGURATION_CREATION_TIME DATETIME    NOT NULL,
    CHANNEL_CONFIG_ID                               BIGINT(11)  NOT NULL,
    BOT_FEATURE_TYPE_ID                             BIGINT(11)  NOT NULL,
    CHANNEL_BOT_FEATURE_CONFIGURATION_IS_ACTIVE     TINYINT(1)  NOT NULL,
    PRIMARY KEY (CHANNEL_BOT_FEATURE_CONFIGURATION_ID),
    KEY SN_FK_CHANNEL_CONFIG_1_IDX  (CHANNEL_CONFIG_ID),
    KEY SN_FK_BOT_FEATURE_TYPE_1_IDX    (BOT_FEATURE_TYPE_ID),
    CONSTRAINT SN_FK_CHANNEL_CONFIG_1
        FOREIGN KEY (CHANNEL_CONFIG_ID)
            REFERENCES TW_BOT.CHANNEL_CONFIG (CHANNEL_CONFIG_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT SN_FK_BOT_FEATURE_TYPE_1
        FOREIGN KEY (BOT_FEATURE_TYPE_ID)
            REFERENCES TW_BOT.BOT_FEATURE_TYPE (BOT_FEATURE_TYPE_ID)
);

-- Table for ChannelBotFeatureLoggingConfigurationEntity
CREATE TABLE TW_BOT.CHANNEL_BOT_FEATURE_LOGGING_CONFIGURATION
(
    CHANNEL_BOT_FEATURE_LOGGING_CONFIGURATION_ID    BIGINT(11)  NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (CHANNEL_BOT_FEATURE_LOGGING_CONFIGURATION_ID),
    KEY SN_FK_CHANNEL_BOT_FEATURE_LOGGING_CONFIG_1_IDX (CHANNEL_BOT_FEATURE_LOGGING_CONFIGURATION_ID),
    CONSTRAINT  SN_FK_CHANNEL_BOT_FEATURE_LOGGING_CONFIG_1
        FOREIGN KEY (CHANNEL_BOT_FEATURE_LOGGING_CONFIGURATION_ID)
            REFERENCES TW_BOT.CHANNEL_BOT_FEATURE_CONFIGURATION (CHANNEL_BOT_FEATURE_CONFIGURATION_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Table for ChannelBotFeatureDonationConfigurationEntity
CREATE TABLE TW_BOT.CHANNEL_BOT_FEATURE_DONATION_CONFIGURATION
(
    CHANNEL_BOT_FEATURE_DONATION_CONFIGURATION_ID   BIGINT(11)  NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (CHANNEL_BOT_FEATURE_DONATION_CONFIGURATION_ID),
    KEY SN_FK_CHANNEL_BOT_FEATURE_DONATION_CONFIG_1_IDX (CHANNEL_BOT_FEATURE_DONATION_CONFIGURATION_ID),
    CONSTRAINT  SN_FK_CHANNEL_BOT_FEATURE_DONATION_CONFIG_1
        FOREIGN KEY (CHANNEL_BOT_FEATURE_DONATION_CONFIGURATION_ID)
            REFERENCES TW_BOT.CHANNEL_BOT_FEATURE_CONFIGURATION (CHANNEL_BOT_FEATURE_CONFIGURATION_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Table for ChannelBotFeatureFollowConfigurationEntity
CREATE TABLE TW_BOT.CHANNEL_BOT_FEATURE_FOLLOW_CONFIGURATION
(
    CHANNEL_BOT_FEATURE_FOLLOW_CONFIGURATION_ID   BIGINT(11)  NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (CHANNEL_BOT_FEATURE_FOLLOW_CONFIGURATION_ID),
    KEY SN_FK_CHANNEL_BOT_FEATURE_FOLLOW_CONFIG_1_IDX (CHANNEL_BOT_FEATURE_FOLLOW_CONFIGURATION_ID),
    CONSTRAINT  SN_FK_CHANNEL_BOT_FEATURE_FOLLOW_CONFIG_1
        FOREIGN KEY (CHANNEL_BOT_FEATURE_FOLLOW_CONFIGURATION_ID)
            REFERENCES TW_BOT.CHANNEL_BOT_FEATURE_CONFIGURATION (CHANNEL_BOT_FEATURE_CONFIGURATION_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Table for ChannelBotFeatureSubscriptionConfigurationEntity
CREATE TABLE TW_BOT.CHANNEL_BOT_FEATURE_SUBSCRIPTION_CONFIGURATION
(
    CHANNEL_BOT_FEATURE_SUBSCRIPTION_CONFIGURATION_ID   BIGINT(11)  NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (CHANNEL_BOT_FEATURE_SUBSCRIPTION_CONFIGURATION_ID),
    KEY SN_FK_CHANNEL_BOT_FEATURE_SUBSCRIPTION_CONFIG_1_IDX (CHANNEL_BOT_FEATURE_SUBSCRIPTION_CONFIGURATION_ID),
    CONSTRAINT  SN_FK_CHANNEL_BOT_FEATURE_SUBSCRIPTION_CONFIG_1
        FOREIGN KEY (CHANNEL_BOT_FEATURE_SUBSCRIPTION_CONFIGURATION_ID)
            REFERENCES TW_BOT.CHANNEL_BOT_FEATURE_CONFIGURATION (CHANNEL_BOT_FEATURE_CONFIGURATION_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Table for ChannelBotFeatureAliveConfigurationEntity
CREATE TABLE TW_BOT.CHANNEL_BOT_FEATURE_ALIVE_CONFIGURATION
(
    CHANNEL_BOT_FEATURE_ALIVE_CONFIGURATION_ID   BIGINT(11)  NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (CHANNEL_BOT_FEATURE_ALIVE_CONFIGURATION_ID),
    KEY SN_FK_CHANNEL_BOT_FEATURE_ALIVE_CONFIG_1_IDX (CHANNEL_BOT_FEATURE_ALIVE_CONFIGURATION_ID),
    CONSTRAINT  SN_FK_CHANNEL_BOT_FEATURE_ALIVE_CONFIG_1
        FOREIGN KEY (CHANNEL_BOT_FEATURE_ALIVE_CONFIGURATION_ID)
            REFERENCES TW_BOT.CHANNEL_BOT_FEATURE_CONFIGURATION (CHANNEL_BOT_FEATURE_CONFIGURATION_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Table for ChannelBotFeatureCommandConfigurationEntity
CREATE TABLE TW_BOT.CHANNEL_BOT_FEATURE_COMMAND_CONFIGURATION
(
    CHANNEL_BOT_FEATURE_COMMAND_CONFIGURATION_ID    BIGINT(11)  NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (CHANNEL_BOT_FEATURE_COMMAND_CONFIGURATION_ID),
    KEY SN_FK_CHANNEL_BOT_FEATURE_COMMAND_CONFIG_1_IDX (CHANNEL_BOT_FEATURE_COMMAND_CONFIGURATION_ID),
    CONSTRAINT  SN_FK_CHANNEL_BOT_FEATURE_COMMAND_CONFIG_1
        FOREIGN KEY (CHANNEL_BOT_FEATURE_COMMAND_CONFIGURATION_ID)
            REFERENCES TW_BOT.CHANNEL_BOT_FEATURE_CONFIGURATION (CHANNEL_BOT_FEATURE_CONFIGURATION_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Table for BotCommandEntity
CREATE TABLE TW_BOT.BOT_COMMAND_TYPE
(
    BOT_COMMAND_TYPE_ID              BIGINT(11)  NOT NULL AUTO_INCREMENT,
    BOT_COMMAND_TYPE_TIMESTAMP       BIGINT(11)  NOT NULL,
    BOT_COMMAND_TYPE_CREATION_TIME   DATETIME    NOT NULL,
    BOT_COMMAND_TYPE_CODE            VARCHAR(45) NOT NULL,
    PRIMARY KEY (BOT_COMMAND_TYPE_ID)
);

-- Table for BotCommandConfigurationEntity
CREATE TABLE TW_BOT.BOT_COMMAND_CONFIGURATION
(
    BOT_COMMAND_CONFIGURATION_ID                    BIGINT(11)  NOT NULL AUTO_INCREMENT,
    BOT_COMMAND_CONFIGURATION_TIMESTAMP             BIGINT(11)  NOT NULL,
    BOT_COMMAND_CONFIGURATION_CREATION_TIME         DATETIME    NOT NULL,
    CHANNEL_BOT_FEATURE_COMMAND_CONFIGURATION_ID    BIGINT(11)  NOT NULL,
    BOT_COMMAND_CONFIGURATION_IS_ACTIVE             TINYINT(1)  NOT NULL,
    BOT_COMMAND_TYPE_ID                             BIGINT(11)  NOT NULL,
    PRIMARY KEY (BOT_COMMAND_CONFIGURATION_ID),
    KEY SN_FK_CHANNEL_BOT_FEATURE_COMMAND_CONFIGURATION_1_IDX (CHANNEL_BOT_FEATURE_COMMAND_CONFIGURATION_ID),
    KEY SN_FK_BOT_COMMAND_TYPE_1_IDX (BOT_COMMAND_TYPE_ID),
    CONSTRAINT SN_FK_CHANNEL_BOT_FEATURE_COMMAND_CONFIGURATION_1
        FOREIGN KEY (CHANNEL_BOT_FEATURE_COMMAND_CONFIGURATION_ID)
            REFERENCES TW_BOT.CHANNEL_BOT_FEATURE_COMMAND_CONFIGURATION (CHANNEL_BOT_FEATURE_COMMAND_CONFIGURATION_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT SN_FK_BOT_COMMAND_TYPE_1
        FOREIGN KEY (BOT_COMMAND_TYPE_ID)
            REFERENCES TW_BOT.BOT_COMMAND_TYPE (BOT_COMMAND_TYPE_ID)
);

-- Table for BotCommandSimpleResponseConfigurationEntity
CREATE TABLE TW_BOT.BOT_COMMAND_SIMPLE_RESPONSE_CONFIGURATION
(
    BOT_COMMAND_SIMPLE_RESPONSE_CONFIGURATION_ID    BIGINT(11)  NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (BOT_COMMAND_SIMPLE_RESPONSE_CONFIGURATION_ID),
    KEY SN_FK_BOT_COMMAND_SIMPLE_RESPONSE_CONFIGURATION_1_IDX (BOT_COMMAND_SIMPLE_RESPONSE_CONFIGURATION_ID),
    CONSTRAINT  SN_FK_BOT_COMMAND_SIMPLE_RESPONSE_CONFIGURATION_1
        FOREIGN KEY (BOT_COMMAND_SIMPLE_RESPONSE_CONFIGURATION_ID)
            REFERENCES TW_BOT.BOT_COMMAND_CONFIGURATION (BOT_COMMAND_CONFIGURATION_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Table for BotCommandTriggerEntity
CREATE TABLE TW_BOT.BOT_COMMAND_TRIGGER
(
    BOT_COMMAND_TRIGGER_ID              BIGINT(11)  NOT NULL AUTO_INCREMENT,
    BOT_COMMAND_TRIGGER_TIMESTAMP       BIGINT(11)  NOT NULL,
    BOT_COMMAND_TRIGGER_CREATION_TIME   DATETIME    NOT NULL,
    BOT_COMMAND_CONFIGURATION_ID        BIGINT(11)  NOT NULL,
    BOT_COMMAND_TRIGGER_VALUE           VARCHAR(20) NOT NULL,
    PRIMARY KEY (BOT_COMMAND_TRIGGER_ID),
    KEY SN_FK_BOT_COMMAND_CONFIGURATION_1_IDX (BOT_COMMAND_CONFIGURATION_ID),
    CONSTRAINT SN_FK_BOT_COMMAND_CONFIGURATION_1
        FOREIGN KEY (BOT_COMMAND_CONFIGURATION_ID)
            REFERENCES TW_BOT.BOT_COMMAND_CONFIGURATION (BOT_COMMAND_CONFIGURATION_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Table for BotCommandActionTypeEntity
CREATE TABLE TW_BOT.BOT_COMMAND_ACTION_TYPE
(
    BOT_COMMAND_ACTION_TYPE_ID              BIGINT(11)  NOT NULL AUTO_INCREMENT,
    BOT_COMMAND_ACTION_TYPE_TIMESTAMP       BIGINT(11)  NOT NULL,
    BOT_COMMAND_ACTION_TYPE_CREATION_TIME   DATETIME    NOT NULL,
    BOT_COMMAND_ACTION_TYPE_CODE            VARCHAR(45) NOT NULL,
    PRIMARY KEY (BOT_COMMAND_ACTION_TYPE_ID)
);

-- Table for BotCommandActionEntity
CREATE TABLE TW_BOT.BOT_COMMAND_ACTION
(
    BOT_COMMAND_ACTION_ID               BIGINT(11)  NOT NULL AUTO_INCREMENT,
    BOT_COMMAND_ACTION_TIMESTAMP        BIGINT(11)  NOT NULL,
    BOT_COMMAND_ACTION_CREATION_TIME    DATETIME    NOT NULL,
    BOT_COMMAND_CONFIGURATION_ID        BIGINT(11)  NOT NULL,
    BOT_COMMAND_ACTION_TYPE_ID          BIGINT(11)  NOT NULL,
    PRIMARY KEY (BOT_COMMAND_ACTION_ID),
    KEY SN_FK_BOT_COMMAND_CONFIGURATION_2_IDX (BOT_COMMAND_CONFIGURATION_ID),
    KEY SN_FK_BOT_COMMAND_ACTION_TYPE_1_IDX (BOT_COMMAND_ACTION_TYPE_ID),
    CONSTRAINT SN_FK_BOT_COMMAND_CONFIGURATION_2
        FOREIGN KEY (BOT_COMMAND_CONFIGURATION_ID)
            REFERENCES TW_BOT.BOT_COMMAND_CONFIGURATION (BOT_COMMAND_CONFIGURATION_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT SN_FK_BOT_COMMAND_ACTION_TYPE_1
        FOREIGN KEY (BOT_COMMAND_ACTION_TYPE_ID)
            REFERENCES TW_BOT.BOT_COMMAND_ACTION_TYPE (BOT_COMMAND_ACTION_TYPE_ID)
);

-- Table for BotCommandSimpleResponseActionEntity
CREATE TABLE TW_BOT.BOT_COMMAND_SIMPLE_RESPONSE_ACTION
(
    BOT_COMMAND_SIMPLE_RESPONSE_ACTION_ID                   BIGINT(11)      NOT NULL AUTO_INCREMENT,
    BOT_COMMAND_SIMPLE_RESPONSE_ACTION_RESPONSE_TEMPLATE    VARCHAR(255)    NULL,
    PRIMARY KEY (BOT_COMMAND_SIMPLE_RESPONSE_ACTION_ID),
    KEY SN_FK_BOT_COMMAND_SIMPLE_RESPONSE_ACTION_1_IDX (BOT_COMMAND_SIMPLE_RESPONSE_ACTION_ID),
    CONSTRAINT  SN_FK_BOT_COMMAND_SIMPLE_RESPONSE_ACTION_1
        FOREIGN KEY (BOT_COMMAND_SIMPLE_RESPONSE_ACTION_ID)
            REFERENCES TW_BOT.BOT_COMMAND_ACTION (BOT_COMMAND_ACTION_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- -----------------------------------
-- ---------- Many-to-Many -----------
-- -----------------------------------

-- Table for many-to-many bidirectional GlobalConfigurationEntity.globalBotAdmins
CREATE TABLE TW_BOT.GLOBAL_CONFIG_GLOBAL_BOT_ADMIN
(
    GLOBAL_CONFIG_CHANNEL_ID    BIGINT(11) NOT NULL AUTO_INCREMENT,
    GLOBAL_CONFIG_ID            BIGINT(11) NOT NULL,
    CHANNEL_ID                  BIGINT(11) NOT NULL,
    PRIMARY KEY (GLOBAL_CONFIG_CHANNEL_ID),
    KEY UR_FK_GLOBAL_CONFIG_IDX (GLOBAL_CONFIG_ID),
    KEY UR_FK_CHANNEL_IDX       (CHANNEL_ID),
    CONSTRAINT UR_FK_GLOBAL_CONFIG
        FOREIGN KEY (GLOBAL_CONFIG_ID)
            REFERENCES TW_BOT.GLOBAL_CONFIG (GLOBAL_CONFIG_ID) ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT UR_FK_CHANNEL
        FOREIGN KEY (CHANNEL_ID)
            REFERENCES TW_BOT.CHANNEL (CHANNEL_ID) ON DELETE NO ACTION ON UPDATE CASCADE
);

-- Table for many-to-many unidirectional GlobalConfigurationEntity.activeGlobalFeatures
CREATE TABLE TW_BOT.GLOBAL_CONFIG_GLOBAL_FEATURE
(
    GLOBAL_CONFIG_BOT_FEATURE_ID    BIGINT(11) NOT NULL AUTO_INCREMENT,
    GLOBAL_CONFIG_ID                BIGINT(11) NOT NULL,
    BOT_FEATURE_TYPE_ID                  BIGINT(11) NOT NULL,
    PRIMARY KEY (GLOBAL_CONFIG_BOT_FEATURE_ID),
    KEY UR_FK_GLOBAL_CONFIG_2_IDX   (GLOBAL_CONFIG_ID),
    KEY UR_FK_BOT_FEATURE_TYPE_1_IDX  (BOT_FEATURE_TYPE_ID),
    CONSTRAINT UR_FK_GLOBAL_CONFIG_2
        FOREIGN KEY (GLOBAL_CONFIG_ID)
            REFERENCES TW_BOT.GLOBAL_CONFIG (GLOBAL_CONFIG_ID) ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT UR_FK_BOT_FEATURE_TYPE_1
        FOREIGN KEY (BOT_FEATURE_TYPE_ID)
            REFERENCES TW_BOT.BOT_FEATURE_TYPE (BOT_FEATURE_TYPE_ID) ON DELETE NO ACTION ON UPDATE CASCADE
);

-- Table for many-to-many bidirectional ChannelConfigurationEntity.channelBotAdmins
CREATE TABLE TW_BOT.CHANNEL_CONFIG_CHANNEL_BOT_ADMIN
(
    CHANNEL_CONFIG_CHANNEL_ID   BIGINT(11) NOT NULL AUTO_INCREMENT,
    CHANNEL_CONFIG_ID           BIGINT(11) NOT NULL,
    CHANNEL_ID                  BIGINT(11) NOT NULL,
    PRIMARY KEY (CHANNEL_CONFIG_CHANNEL_ID),
    KEY UR_FK_CHANNEL_CONFIG_IDX    (CHANNEL_CONFIG_ID),
    KEY UR_FK_CHANNEL_2_IDX         (CHANNEL_ID),
    CONSTRAINT UR_FK_CHANNEL_CONFIG
        FOREIGN KEY (CHANNEL_CONFIG_ID)
            REFERENCES TW_BOT.CHANNEL_CONFIG (CHANNEL_CONFIG_ID) ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT UR_FK_CHANNEL_2
        FOREIGN KEY (CHANNEL_ID)
            REFERENCES TW_BOT.CHANNEL (CHANNEL_ID) ON DELETE NO ACTION ON UPDATE CASCADE
);

-- Table for many-to-many unidirectional ChannelConfigurationEntity.availableChannelFeatures
CREATE TABLE TW_BOT.CHANNEL_CONFIG_AVAILABLE_CHANNEL_FEATURE
(
    CHANNEL_CONFIG_BOT_FEATURE_ID   BIGINT(11) NOT NULL AUTO_INCREMENT,
    CHANNEL_CONFIG_ID               BIGINT(11) NOT NULL,
    BOT_FEATURE_TYPE_ID                  BIGINT(11) NOT NULL,
    PRIMARY KEY (CHANNEL_CONFIG_BOT_FEATURE_ID),
    KEY UR_FK_CHANNEL_CONFIG_2_IDX      (CHANNEL_CONFIG_ID),
    KEY UR_FK_BOT_FEATURE_TYPE_2_IDX    (BOT_FEATURE_TYPE_ID),
    CONSTRAINT UR_FK_CHANNEL_CONFIG_2
        FOREIGN KEY (CHANNEL_CONFIG_ID)
            REFERENCES TW_BOT.CHANNEL_CONFIG (CHANNEL_CONFIG_ID) ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT UR_FK_BOT_FEATURE_TYPE_2
        FOREIGN KEY (BOT_FEATURE_TYPE_ID)
            REFERENCES TW_BOT.BOT_FEATURE_TYPE (BOT_FEATURE_TYPE_ID) ON DELETE NO ACTION ON UPDATE CASCADE
);

-- Table for many-to-many unidirectional GlobalConfigurationEntity.ignoredUsers
CREATE TABLE TW_BOT.GLOBAL_CONFIG_IGNORED_USER
(
    GLOBAL_CONFIG_CHANNEL_ID    BIGINT(11) NOT NULL AUTO_INCREMENT,
    GLOBAL_CONFIG_ID            BIGINT(11) NOT NULL,
    CHANNEL_ID                  BIGINT(11) NOT NULL,
    PRIMARY KEY (GLOBAL_CONFIG_CHANNEL_ID),
    KEY UR_FK_GLOBAL_CONFIG_3_IDX   (GLOBAL_CONFIG_ID),
    KEY UR_FK_BOT_CHANNEL_3_IDX     (CHANNEL_ID),
    CONSTRAINT UR_FK_GLOBAL_CONFIG_3
        FOREIGN KEY (GLOBAL_CONFIG_ID)
            REFERENCES TW_BOT.GLOBAL_CONFIG (GLOBAL_CONFIG_ID) ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT UR_FK_CHANNEL_3
        FOREIGN KEY (CHANNEL_ID)
            REFERENCES TW_BOT.CHANNEL (CHANNEL_ID) ON DELETE NO ACTION ON UPDATE CASCADE
);

-- Table for many-to-many unidirectional ChannelConfigurationEntity.ignoredUsers
CREATE TABLE TW_BOT.CHANNEL_CONFIG_IGNORED_USER
(
    CHANNEL_CONFIG_CHANNEL_ID   BIGINT(11) NOT NULL AUTO_INCREMENT,
    CHANNEL_CONFIG_ID           BIGINT(11) NOT NULL,
    CHANNEL_ID                  BIGINT(11) NOT NULL,
    PRIMARY KEY (CHANNEL_CONFIG_CHANNEL_ID),
    KEY UR_FK_CHANNEL_CONFIG_3_IDX  (CHANNEL_CONFIG_ID),
    KEY UR_FK_BOT_CHANNEL_4_IDX     (CHANNEL_ID),
    CONSTRAINT UR_FK_CHANNEL_CONFIG_3
        FOREIGN KEY (CHANNEL_CONFIG_ID)
            REFERENCES TW_BOT.CHANNEL_CONFIG (CHANNEL_CONFIG_ID) ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT UR_FK_CHANNEL_4
        FOREIGN KEY (CHANNEL_ID)
            REFERENCES TW_BOT.CHANNEL (CHANNEL_ID) ON DELETE NO ACTION ON UPDATE CASCADE
);

-- Table for many-to-many unidirectional BotCommandConfigurationEntity.availableCommandActionTypes
CREATE TABLE TW_BOT.BOT_COMMAND_CONFIGURATION_BOT_COMMAND_ACTION_TYPE
(
    BOT_COMMAND_CONFIGURATION_BOT_COMMAND_ACTION_TYPE_ID    BIGINT(11) NOT NULL AUTO_INCREMENT,
    BOT_COMMAND_CONFIGURATION_ID                            BIGINT(11) NOT NULL,
    BOT_COMMAND_ACTION_TYPE_ID                              BIGINT(11) NOT NULL,
    PRIMARY KEY (BOT_COMMAND_CONFIGURATION_BOT_COMMAND_ACTION_TYPE_ID),
    KEY UR_FK_BOT_COMMAND_CONFIGURATION_1_IDX   (BOT_COMMAND_CONFIGURATION_ID),
    KEY UR_FK_BOT_COMMAND_ACTION_TYPE_1_IDX     (BOT_COMMAND_ACTION_TYPE_ID),
    CONSTRAINT UR_FK_COMMAND_CONFIGURATION_1
        FOREIGN KEY (BOT_COMMAND_CONFIGURATION_ID)
            REFERENCES TW_BOT.BOT_COMMAND_CONFIGURATION (BOT_COMMAND_CONFIGURATION_ID) ON DELETE NO ACTION ON UPDATE CASCADE,
    CONSTRAINT UR_FK_BOT_COMMAND_ACTION_TYPE_1
        FOREIGN KEY (BOT_COMMAND_ACTION_TYPE_ID)
            REFERENCES TW_BOT.BOT_COMMAND_ACTION_TYPE (BOT_COMMAND_ACTION_TYPE_ID) ON DELETE NO ACTION ON UPDATE CASCADE
);
