
-- Insert for ChannelConfigurationEntity
INSERT INTO TW_BOT.CHANNEL_CONFIG (CHANNEL_CONFIG_ID, CHANNEL_CONFIG_TIMESTAMP, CHANNEL_CONFIG_CREATION_TIME)
VALUES (1, 0, NOW());

UPDATE TW_BOT.CHANNEL SET CHANNEL_CONFIG_ID = 1 WHERE CHANNEL_ID = 1;

-- Insert for ChannelConfigurationEntity.activeChannelFeatures
INSERT INTO TW_BOT.CHANNEL_CONFIG_AVAILABLE_CHANNEL_FEATURE (CHANNEL_CONFIG_BOT_FEATURE_ID, CHANNEL_CONFIG_ID, BOT_FEATURE_TYPE_ID)
VALUES (1, 1, 1),
       (2, 1, 2),
       (3, 1, 3),
       (4, 1, 4),
       (5, 1, 5),
       (6, 1, 6);

-- Insert for ChannelBotFeatureConfigurationEntity
INSERT INTO TW_BOT.CHANNEL_BOT_FEATURE_CONFIGURATION (CHANNEL_BOT_FEATURE_CONFIGURATION_ID, CHANNEL_BOT_FEATURE_CONFIGURATION_TIMESTAMP, CHANNEL_BOT_FEATURE_CONFIGURATION_CREATION_TIME, CHANNEL_CONFIG_ID, BOT_FEATURE_TYPE_ID, CHANNEL_BOT_FEATURE_CONFIGURATION_IS_ACTIVE)
VALUES (1, 0, NOW(), 1, 1, 1),
       (2, 0, NOW(), 1, 2, 1),
       (3, 0, NOW(), 1, 3, 1),
       (4, 0, NOW(), 1, 4, 1),
       (5, 0, NOW(), 1, 5, 1),
       (6, 0, NOW(), 1, 6, 1);

-- Insert for ChannelBotFeatureLoggingConfigurationEntity
INSERT INTO TW_BOT.CHANNEL_BOT_FEATURE_LOGGING_CONFIGURATION (CHANNEL_BOT_FEATURE_LOGGING_CONFIGURATION_ID)
VALUES (1);

-- Insert for ChannelBotFeatureDonationConfigurationEntity
INSERT INTO TW_BOT.CHANNEL_BOT_FEATURE_DONATION_CONFIGURATION (CHANNEL_BOT_FEATURE_DONATION_CONFIGURATION_ID)
VALUES (2);

-- Insert for ChannelBotFeatureSubscriptionConfigurationEntity
INSERT INTO TW_BOT.CHANNEL_BOT_FEATURE_FOLLOW_CONFIGURATION (CHANNEL_BOT_FEATURE_FOLLOW_CONFIGURATION_ID)
VALUES (3);

-- Insert for ChannelBotFeatureSubscriptionConfigurationEntity
INSERT INTO TW_BOT.CHANNEL_BOT_FEATURE_SUBSCRIPTION_CONFIGURATION (CHANNEL_BOT_FEATURE_SUBSCRIPTION_CONFIGURATION_ID)
VALUES (4);

-- Insert for ChannelBotFeatureCommandConfigurationEntity
INSERT INTO TW_BOT.CHANNEL_BOT_FEATURE_COMMAND_CONFIGURATION (CHANNEL_BOT_FEATURE_COMMAND_CONFIGURATION_ID)
VALUES (5);

-- Insert for ChannelBotFeatureAliveConfigurationEntity
INSERT INTO TW_BOT.CHANNEL_BOT_FEATURE_ALIVE_CONFIGURATION (CHANNEL_BOT_FEATURE_ALIVE_CONFIGURATION_ID)
VALUES (6);

-- Insert for BotCommandConfigurationEntity
INSERT INTO TW_BOT.BOT_COMMAND_CONFIGURATION (BOT_COMMAND_CONFIGURATION_ID, BOT_COMMAND_CONFIGURATION_TIMESTAMP, BOT_COMMAND_CONFIGURATION_CREATION_TIME, CHANNEL_BOT_FEATURE_COMMAND_CONFIGURATION_ID, BOT_COMMAND_CONFIGURATION_IS_ACTIVE, BOT_COMMAND_TYPE_ID)
VALUES (1, 0, NOW(), 5, 1, 1);

-- Insert for BotCommandSimpleResponseConfigurationEntity
INSERT INTO TW_BOT.BOT_COMMAND_SIMPLE_RESPONSE_CONFIGURATION (BOT_COMMAND_SIMPLE_RESPONSE_CONFIGURATION_ID)
VALUES (1);

-- Insert for BotCommandTriggerEntity
INSERT INTO TW_BOT.BOT_COMMAND_TRIGGER (BOT_COMMAND_TRIGGER_ID, BOT_COMMAND_TRIGGER_TIMESTAMP, BOT_COMMAND_TRIGGER_CREATION_TIME, BOT_COMMAND_CONFIGURATION_ID, BOT_COMMAND_TRIGGER_VALUE)
VALUES (1, 0, NOW(), 1, 'test1'),
       (2, 0, NOW(), 1, 'test2');

-- Insert for BotCommandConfigurationEntity.availableCommandActionTypes
INSERT INTO TW_BOT.BOT_COMMAND_CONFIGURATION_BOT_COMMAND_ACTION_TYPE (BOT_COMMAND_CONFIGURATION_BOT_COMMAND_ACTION_TYPE_ID, BOT_COMMAND_CONFIGURATION_ID, BOT_COMMAND_ACTION_TYPE_ID)
VALUES (1, 1, 1);

-- Insert for BotCommandActionEntity
INSERT INTO TW_BOT.BOT_COMMAND_ACTION (BOT_COMMAND_ACTION_ID, BOT_COMMAND_ACTION_TIMESTAMP, BOT_COMMAND_ACTION_CREATION_TIME, BOT_COMMAND_ACTION_TYPE_ID, BOT_COMMAND_CONFIGURATION_ID)
VALUES (1, 0, NOW(), 1, 1);

-- Insert for BotCommandSimpleResponseActionEntity
INSERT INTO TW_BOT.BOT_COMMAND_SIMPLE_RESPONSE_ACTION (BOT_COMMAND_SIMPLE_RESPONSE_ACTION_ID, BOT_COMMAND_SIMPLE_RESPONSE_ACTION_RESPONSE_TEMPLATE)
VALUES (1, 'test response');
